export const ADD_STRUCTURE = 'ADD_STRUCTURE';
export const ADD_STRUCTURES = 'ADD_STRUCTURES';
export const DELETE_STRUCTURE = 'DELETE_STRUCTURE';
export const EDIT_STRUCTURE = 'EDIT_STRUCTURE';
export const TRIGGER_MODAL = 'TRIGGER_MODAL';
export const ADD_SETTINGS = 'ADD_SETTINGS';

export const SAGA_INIT_STRUCTURE_LIST_PAGE = 'SAGA_INIT_STRUCTURE_LIST_PAGE';
export const SAGA_ADD_STRUCTURE = 'SAGA_ADD_STRUCTURE';
export const SAGA_DELETE_STRUCTURE = 'SAGA_DELETE_STRUCTURE';
export const SAGA_EDIT_STRUCTURE = 'SAGA_EDIT_STRUCTURE';