export const ADD_STRUCTURE = 'ADD_STRUCTURE';
export const ADD_STRUCTURES = 'ADD_STRUCTURES';
export const DELETE_STRUCTURE = 'DELETE_STRUCTURE';
export const EDIT_STRUCTURE = 'EDIT_STRUCTURE';
export const TRIGGER_MODAL = 'TRIGGER_MODAL';
export const ADD_SETTINGS = 'ADD_SETTINGS';