// for index page
export const ADD_STRUCTURE_INDEX = 'ADD_STRUCTURE';
export const EDIT_STRUCTURE_INDEX = 'EDIT_STRUCTURE';
export const DELETE_STRUCTURE_INDEX = 'DELETE_STRUCTURE';

// for validate page
export const ADD_STRUCTURES_VALIDATE = 'ADD_STRUCTURES_VALIDATE';
export const EDIT_STRUCTURE_VALIDATE = 'EDIT_STRUCTURE_VALIDATE';
// for result page
export const ADD_STRUCTURE_RESULT = 'ADD_STRUCTURE_RESULT';

// sagas
export const SAGA_INIT_VALIDATE_PAGE = 'SAGA_INIT_VALIDATE_PAGE';
export const SAGA_INIT_RESULT_PAGE = 'SAGA_INIT_RESULT_PAGE';
export const SAGA_EDIT_STRUCTURE_VALIDATE = 'SAGA_EDIT_STRUCTURE_VALIDATE';
export const SAGA_CREATE_TASK_INDEX = 'SAGA_CREATE_TASK_INDEX';
export const SAGA_NEW_STRUCTURE = 'SAGA_NEW_STRUCTURE';
export const SAGA_NEW_STRUCTURE_CALLBACK = 'SAGA_NEW_STRUCTURE_CALLBACK';
export const SAGA_EDIT_STRUCTURE_INDEX = 'SAGA_EDIT_STRUCTURE_INDEX';
export const SAGA_CREATE_RESULT_TASK = 'SAGA_CREATE_RESULT_TASK';
export const SAGA_DELETE_STRUCRURES_VALIDATE_PAGE = 'SAGA_DELETE_STRUCRURES_VALIDATE_PAGE';
export const SAGA_EDIT_STRUCTURE_VALIDATE_CALLBACK = 'SAGA_EDIT_STRUCTURE_VALIDATE_CALLBACK';
export const SAGA_EDIT_STRUCTURE_INDEX_CALLBACK = 'SAGA_EDIT_STRUCTURE_INDEX_CALLBACK';
export const SAGA_REVALIDATE_VALIDATE_PAGE = 'SAGA_REVALIDATE_VALIDATE_PAGE';