// for index page
export const ADD_STRUCTURE_INDEX = 'ADD_STRUCTURE';
export const EDIT_STRUCTURE_INDEX = 'EDIT_STRUCTURE';
export const DELETE_STRUCTURE_INDEX = 'DELETE_STRUCTURE';

// for validate page
export const ADD_STRUCTURES_VALIDATE = 'ADD_STRUCTURES_VALIDATE';

export const ADD_TEMPERATURE_VALIDATE = 'ADD_TEMPERATURE_VALIDATE';
export const ADD_PRESSURE_VALIDATE = 'ADD_PRESSURE_VALIDATE';
export const ADD_MODELS_VALIDATE = 'ADD_MODELS_VALIDATE';
export const ADD_ADDITIVES_VALIDATE = 'ADD_ADDITIVES_VALIDATE';

// all additives
export const ADD_ALL_ADDITIVES = 'ADD_ALL_ADDITIVES';

// all models
export const ADD_ALL_MODELS = 'ADD_ALL_MODELS';

