export const TRIGGER = 'TRIGGER';

export const STRUCTURE = {
  ADD_STRUCTURE: 'ADD_STRUCTURE',
  EDIT_STRUCTURE: 'EDIT_STRUCTURE',
  ADD_SELECTED_MODEL: 'ADD_SELECTED_MODEL',
};

export const MODELS = {
  ADD: 'ADD_MODELS',
  SELECT: 'SELECT',
};

export const RESULT = {
  ADD: 'ADD_RESULT',
};

export const HISTORY = {
  ADD: 'ADD_HISTORY',
};

export const REQUEST = {
  START_REQUEST: 'START_REQUEST',
  SUCCESS_REQUEST: 'SUCCESS_REQUEST',
  ERROR_REQUEST: 'ERROR_REQUEST',
};
