export const STRUCTURE = {
  ADD_STRUCTURE: 'ADD_STRUCTURE',
  EDIT_STRUCTURE: 'EDIT_STRUCTURE',
  ADD_SELECTED_MODEL: 'ADD_SELECTED_MODEL',
};

export const MODELS = {
  ADD: 'ADD_MODELS',
  SELECT: 'SELECT',
};

export const RESULT = {
  ADD: 'ADD_RESULT',
};

export const HISTORY = {
  ADD: 'ADD_HISTORY',
};

export const SAGA_CREATE_TASK = 'SAGA_CREATE_TASK';
export const SAGA_INIT_VALIDATE_PAGE = 'SAGA_INIT_VALIDATE_PAGE';
export const SAGA_CREATE_RESULT_TASK = 'SAGA_CREATE_RESULT_TASK';
export const SAGA_INIT_RESULT_PAGE = 'SAGA_INIT_RESULT_PAGE';
export const SAGA_DRAW_STRUCTURE = 'SAGA_DRAW_STRUCTURE';
export const SAGA_CREATE_TASK_SEARCH = 'SAGA_CREATE_TASK_SEARCH';
export const SAGA_EDIT_STRUCTURE_1 = 'SAGA_EDIT_STRUCTURE_1';
export const SAGA_EDIT_TASK_SEARCH = 'SAGA_EDIT_TASK_SEARCH';
export const SAGA_REVALIDATE_TASK = 'SAGA_REVALIDATE_TASK';

