export const REQUEST = {
  START_REQUEST: 'START_REQUEST',
  SUCCESS_REQUEST: 'SUCCESS_REQUEST',
  ERROR_REQUEST: 'ERROR_REQUEST',
};

export const TRIGGER = 'TRIGGER';

export const BASE_DATA = {
  ADD_ALL_ADDITIVES: 'ADD_ALL_ADDITIVES',
  ADD_ALL_MODELS: 'ADD_ALL_MODELS',
  ADD_MAGIC: 'ADD_MAGIC',
};
